[package]
name = "myujikbot"
version = "0.1.0"
edition = "2021"

[dependencies]
serenity = "0.11"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread", "signal"] }
songbird = "0.3.2"
dotenv = "0.15.0"
tracing = "0.1"
tracing-subscriber = "0.2"
tracing-futures = "0.2"